Repository home-assistant-libs/python-go2rtc-client, pull requests merged in 2024-10, with the labels that each got.

#1 Activate all ruff rules
  go2rtc_client/client.py
  pyproject.toml
  tests/conftest.py
  tests/test_client.py
Labels: enhancement

#6 Use mypy-dev for type checking
  pyproject.toml
  uv.lock
Labels: dependencies

#7 Add common generics to pylint good-names list
  pyproject.toml
Labels: enhancement

#9 Disable ruff FBT001 in tests
  pyproject.toml
Labels: enhancement

#10 Switch to yarl for building the request URL
  go2rtc_client/rest.py
Labels: performance

#8 Catch and wrap aiohttp and mashumaro errors
  go2rtc_client/exceptions.py
  go2rtc_client/rest.py
  go2rtc_client/ws/client.py
Labels: enhancement

#5 Add method for validating the go2rtc server version is supported
  go2rtc_client/models.py
  go2rtc_client/rest.py
  pyproject.toml
  tests/__snapshots__/test_rest.ambr
  tests/fixtures/application_info_answer.json
  tests/test_rest.py
  uv.lock
Labels: new-feature

#3 Add webrtc audio conversion
  go2rtc_client/rest.py
  tests/test_rest.py
Labels: enhancement

#4 Add ice servers to async WebRTC offer
  .pre-commit-config.yaml
  go2rtc_client/ws/client.py
  go2rtc_client/ws/messages.py
  pyproject.toml
  tests/ws/test_client.py
  uv.lock
Labels: enhancement

#12 Add release workflow
  .github/release-drafter.yml
  .github/workflows/release.yaml
Labels: enhancement

#13 Add a supported version range instead of a single version
  go2rtc_client/rest.py
  tests/test_rest.py
Labels: refactor

#16 Run tests also for Python 3.13
  .github/workflows/ci.yaml
Labels: ci

#14 Require min version of 1.9.5
  go2rtc_client/rest.py
  tests/test_rest.py
Labels: refactor

#15 Add py.typed file
  go2rtc_client/py.typed
Labels: enhancement

#11 Fix ws receive task
  go2rtc_client/ws/client.py
  pyproject.toml
  tests/ws/test_client.py
Labels: bugfix

#18 Decorate validate_server_version and get_info with handle_error
  go2rtc_client/rest.py
Labels: bugfix

#19 Raise in validate_server_version instead of returning a bool
  go2rtc_client/exceptions.py
  go2rtc_client/rest.py
  tests/test_rest.py
Labels: enhancement

#20 Make rest client time out after 10s
  go2rtc_client/rest.py
  tests/test_rest.py
Labels: bugfix

#21 Fix producers can be null
  go2rtc_client/models.py
  tests/__snapshots__/test_rest.ambr
  tests/fixtures/streams_without_producers.json
  tests/test_rest.py
Labels: bugfix
